package com.qiankang.model;
// Generated 2016-3-23 15:00:24 by Hibernate Tools 4.3.1.Final

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private String username;
	private String passwd;

	public User() {
	}

	public User(String username, String passwd) {
		this.username = username;
		this.passwd = passwd;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPasswd() {
		return this.passwd;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

}
